readonly branch=16-qpr2
readonly aosp_tag_old=android-16.0.0_r4
readonly aosp_tag=android-16.0.0_r4

user_error() {
    echo $1 >&2
    exit 1
}

readonly aosp_forks=(
    device_common
    device_generic_goldfish
    platform_art
    platform_bionic
    platform_bootable_recovery
    platform_build
    platform_build_release
    platform_build_soong
    platform_development
    platform_external_conscrypt
    platform_external_dng_sdk
    platform_external_libpng
    platform_external_protobuf
    platform_external_selinux
    platform_external_sqlite
    platform_frameworks_av
    platform_frameworks_base
    platform_frameworks_libs_systemui
    platform_frameworks_native
    platform_frameworks_opt_net_wifi
    platform_frameworks_opt_telephony
    platform_hardware_st_nfc
    platform_libcore
    platform_packages_apps_Calendar
    platform_packages_apps_CellBroadcastReceiver
    platform_packages_apps_Contacts
    platform_packages_apps_Dialer
    platform_packages_apps_DocumentsUI
    platform_packages_apps_EmergencyInfo
    platform_packages_apps_Gallery2
    platform_packages_apps_Launcher3
    platform_packages_apps_Settings
    platform_packages_apps_SettingsIntelligence
    platform_packages_apps_StorageManager
    platform_packages_apps_ThemePicker
    platform_packages_apps_WallpaperPicker2
    platform_packages_inputmethods_LatinIME
    platform_packages_modules_adb
    platform_packages_modules_AppSearch
    platform_packages_modules_Bluetooth
    platform_packages_modules_common
    platform_packages_modules_ConfigInfrastructure
    platform_packages_modules_Connectivity
    platform_packages_modules_DnsResolver
    platform_packages_modules_HealthFitness
    platform_packages_modules_NetworkStack
    platform_packages_modules_Nfc
    platform_packages_modules_Permission
    platform_packages_modules_RemoteKeyProvisioning
    platform_packages_modules_StatsD
    platform_packages_modules_Uwb
    platform_packages_modules_Virtualization
    platform_packages_modules_Wifi
    platform_packages_providers_ContactsProvider
    platform_packages_providers_DownloadProvider
    platform_packages_providers_MediaProvider
    platform_packages_providers_TelephonyProvider
    platform_packages_services_Mms
    platform_packages_services_Telecomm
    platform_packages_services_Telephony
    platform_system_ca-certificates
    platform_system_core
    platform_system_extras
    platform_system_logging
    platform_system_netd
    platform_system_sepolicy
    platform_system_tools_aidl
    platform_system_vold
    platform_tools_apksig
    platform_tools_metalava
)

readonly independent=(
    adevtool
    branding
    device_google_akita-kernels_6.1
    device_google_bluejay-kernels_6.1
    device_google_caimito-kernels_6.1
    device_google_comet-kernels_6.1
    device_google_felix-kernels_6.1
    device_google_laguna-kernels_6.6
    device_google_lynx-kernels_6.1
    device_google_pantah-kernels_6.1
    device_google_raviole-kernels_6.1
    device_google_shusky-kernels_6.1
    device_google_stallion-kernels_6.1
    device_google_tangorpro-kernels_6.1
    device_google_tegu-kernels_6.1
    hardened_malloc
    kernel_common-6.1
    kernel_common-6.6
    kernel_common-6.12
    kernel_manifest-6.1
    kernel_manifest-6.6
    kernel_manifest-6.12
    kernel_pixel
    kernel_pixel_muzel
    platform_external_AppCompatConfig
    platform_external_AppStore
    platform_external_Auditor
    platform_external_Camera
    platform_external_GmsCompatConfig
    platform_external_Info
    platform_external_Messaging
    platform_external_PdfViewer
    platform_external_talkback
    platform_external_vanadium
    platform_manifest
    platform_packages_apps_AppCompatConfig
    platform_packages_apps_CarrierConfig2
    platform_packages_apps_DeskClock
    platform_packages_apps_ExactCalculator
    platform_packages_apps_GmsCompat
    platform_packages_apps_LogViewer
    platform_packages_apps_NetworkLocation
    platform_packages_apps_Seedvault
    platform_packages_apps_SetupWizard2
    platform_packages_apps_Updater
    platform_prebuilts_qemu-kernel
    platform_tools_arsclib
    script
    vendor_state
)

readonly signing_keys=(
    bluetooth
    gmscompat_lib
    media
    networkstack
    nfc
    platform
    releasekey
    sdk_sandbox
    shared
)
