#!/bin/bash

set -o errexit -o nounset -o pipefail

devices=(raviole bluejay pantah lynx tangorpro felix shusky akita caimito comet tegu)
parallel 'rm -rf build/{} && cp -a pixel build/{}' ::: ${devices[@]}
